#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/arch/.Xmodmap"

# Export the xscreensaver path
export PATH="$PATH:/usr/lib/xscreensaver"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# wmnd &
# wmsmixer -w &
# idesk &
xscreensaver --no-splash &
glslideshow --root &
unclutter -idle 2 &
nm-applet &
pasystray &
flameshot &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/arch/.fluxbox/log"
